stages:
  - "build"
  - "quality"

image: "golang:1.14"

variables:
  GOPATH: "${CI_PROJECT_DIR}/.go"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  untracked: true
  paths:
    - ".go/"

build:go:
  stage: "build"
  script:
    - "make build-all"
  artifacts:
    paths:
      - nas-cli*

quality:test:
  stage: "quality"
  cache:
    policy: "pull"
  script:
    - "go test"
